# Generated by Django 4.2.1 on 2023-05-22 22:40

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.CharField(max_length=5000)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('home_page', models.URLField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommenterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
                ('severity', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.ForeignKey(default=posts.models.get_default_tag_status, on_delete=django.db.models.deletion.CASCADE, to='posts.tagstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, upload_to='post_images')),
                ('image2', models.ImageField(blank=True, upload_to='post_images')),
                ('image3', models.ImageField(blank=True, upload_to='post_images')),
                ('image4', models.ImageField(blank=True, upload_to='post_images')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('status', models.ForeignKey(default=posts.models.get_default_post_status, on_delete=django.db.models.deletion.CASCADE, to='posts.poststatus')),
                ('tags', models.ManyToManyField(blank=True, to='posts.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.commenter')),
                ('type', models.ForeignKey(default=posts.models.get_default_flag_category, on_delete=django.db.models.deletion.CASCADE, to='posts.flagcategory')),
            ],
        ),
        migrations.AddField(
            model_name='commenter',
            name='status',
            field=models.ForeignKey(default=posts.models.get_default_commenter_status, on_delete=django.db.models.deletion.CASCADE, to='posts.commenterstatus'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.commenter')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('status', models.ForeignKey(default=posts.models.get_default_comment_status, on_delete=django.db.models.deletion.CASCADE, to='posts.commentstatus')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(default=posts.models.get_default_category_status, on_delete=django.db.models.deletion.CASCADE, to='posts.categorystatus'),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.ForeignKey(default=posts.models.get_default_author_status, on_delete=django.db.models.deletion.CASCADE, to='posts.authorstatus'),
        ),
    ]
